import re

ACTUATOR_NAMES = ["BrowOuterLeft",
					"BrowInnerLeft",
					"BrowCenter",
					"BrowInnerRight",
					"UpperLidLeft",
					"BrowOuterRight",
					"UpperLidRight",
					"LowerLidLeft",
					"LowerLidRight",
					"EyeTurnLeft",
					"EyeTurnRight",
					"EyesUpDown",
					"CheekSquintLeft",
					"CheekSquintRight",
					"UpperLipLeft",
					"UpperLipCenter",
					"UpperLipRight",
					"LowerLipLeft",
					"LowerLipCenter",
					"LowerLipRight",
					"LipsStretchLeft",
					"FrownLeft",
					"FrownRight",
					"SmileLeft",
					"SmileRight",
					"Jaw",
					"Tongue",
					"UpperGimbalLeft",
					"UpperGimbalRight",
					"LowerGimbalLeft",
					"LowerGimbalRight",
					"NeckRotation",
					"RightShoulderPitch",
					"RightShoulderRoll",
					"RightShoulderYaw",
					"RightElbowPitch",
					"RightElbowYaw",
					"RightWristPitch",
					"RightWristRoll",
					"RightThumbRoll",
					"RightThumbFinger",
					"RightFingerSpread",
					"RightIndexFinger",
					"RightMiddleFinger",
					"RightRingFinger",
					"RightPinkyFinger",
					"LeftShoulderPitch",
					"LeftShoulderRoll",
					"LeftShoulderYaw",
					"LeftElbowPitch",
					"LeftElbowYaw",
					"LeftWristPitch",
					"LeftWristRoll",
					"LeftThumbRoll",
					"LeftThumbFinger",
					"LeftFingerSpread",
					"LeftIndexFinger",
					"LeftMiddleFinger",
					"LeftRingFinger",
					"LeftPinkyFinger",
					"Base"]

head_actuator_keywords = ["Brow", "Lid", "Eye", "Cheek", "Lip", "Frown", "Smile",
							"Jaw", "Tongue", "Gimbal", "Neck"]

head_actuator_regex = "({})".format("|".join(head_actuator_keywords))
HEAD_ACTUATOR_NAMES = []

for actuator_name in ACTUATOR_NAMES:
	if re.search(head_actuator_regex, actuator_name):
		HEAD_ACTUATOR_NAMES.append(actuator_name)